# ~/.config/ruff/base.toml

# usage:
# in project/ruff.toml
# extend = "~/.config/ruff/base.toml"

indent-width = 2
line-length = 120

[format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[lint]
select = [
  "E",
  "W",
  "F",
  "I",
  "N",
  "UP",
  "B",
  "C4",
  "SIM",
  "TD",
  # "DOC",
  # "D",
  "PL",
  "PLE",
  "PLR",
  "PLW",
  "UP",
  "FURB",
  "RUF",
  "TRY",
]
